### ISSUE TITLE
Tolerations or nodeSelector: error converting YAML to JSON

### ISSUE THREAD

**Issue by kladiv** [vadimkim/cert-manager-webhook-hetzner#6]
Hi @vadimkim ,
thank you for this webook and Helm Chart. I hope it's still supported.

I found an issue if i set "tolerations" and/or nodeSelector keys in values yaml:

```
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: NoSchedule
nodeSelector:
  node-role.kubernetes.io/master: "true"
```

The returned error is:

```
YAML parse error on cert-manager-webhook-hetzner/templates/deployment.yaml: error converting YAML to JSON: yaml: line 58: did not find expected key
```

Are you able to check the template please? Dunno if @dgiebert can help too.
Thank you
