### ISSUE TITLE
Cert that I get looks weird

### ISSUE THREAD

**Issue by 53845714nF** [vadimkim/cert-manager-webhook-hetzner#63]
I used to try to use this tool on my home k3s. 

I don't know the meaning of Group name (dint find it on Hetzner docs and not in the README), so I use my Zone name.
I do all steps in the README. I have seen the TXT Record was created in the Hetzner DNS Console, but after some seconds it was deleted. 

Here is the log of the webhook-hetzner pod:
![grafik](https://github.com/vadimkim/cert-manager-webhook-hetzner/assets/48125666/7c5431b2-943f-432a-b31c-e790f5b5faab)

I am confused, the client IP is `10.42.0.251` this is an internal IP of the cluster. When I want to connect to my master, I use `192.168.178.42`. The remaining log looks pretty normal to me, no errors.

In the end, I have **no** Let's encrypt Cert on my Ingress. (Only the trafik default)
Am I doing something wrong with the Ingress controller or does the error occur earlier?

**Comment by 53845714nF** [comment]
I get a Cert in the Ingress 🎉 
I don't know what I did wrong. 

But the Problem, the Cert look weird: 
![grafik](https://github.com/vadimkim/cert-manager-webhook-hetzner/assets/48125666/909d0f8e-18a4-41b5-86f8-d2f44767775d)
![grafik](https://github.com/vadimkim/cert-manager-webhook-hetzner/assets/48125666/97eb0fe5-bd78-499b-bc01-66121064356b)
![grafik](https://github.com/vadimkim/cert-manager-webhook-hetzner/assets/48125666/48e72fa6-63c5-4834-a1a8-351deb8cee16)
![grafik](https://github.com/vadimkim/cert-manager-webhook-hetzner/assets/48125666/fae2896f-6687-4ec6-9516-29243730a27a)

**Comment by vadimkim** [comment]
Good to hear! 👍

**Comment by 53845714nF** [comment]
Ahh sorry, did you know what's wrong with the Cert?

I have no `verified by` on the cert.
My assumption was that `Lets Encrypt`  would be their.


This is my Issuer: 
```yml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory

    # Email address used for ACME registration
    email: hackwiki2.0@gmail.com

    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging

    solvers:
      - dns01:
          webhook:
            # This group needs to be configured when installing the helm package, otherwise the webhook won't have permission to create an ACME challenge for this API group.
            groupName: hackwiki.de
            solverName: hetzner
            config:
              secretName: hetzner-secret
              zoneName: hackwiki.de # (Optional): When not provided the Zone will searched in Hetzner API by recursion on full domain name
              apiUrl: https://dns.hetzner.com/api/v1
```
