### ISSUE TITLE
unable to get secret `cert-manager`; unable to get secret `/cert-manager`; resource name may not be empty

### ISSUE THREAD

**Issue by matthias-hampel** [vadimkim/cert-manager-webhook-hetzner#84]
I get the error message `unable to get secret `cert-manager`; unable to get secret `/cert-manager`; resource name may not be empty` when trying to retrieve a certificate.

This is the error message from the cert-manager pod:
```
I0226 16:11:44.490477       1 dns.go:90] "presenting DNS01 challenge for domain" logger="cert-manager.controller.Present" resource_name="chart-example-tls-1-3937858742-2111318442" resource_namespace="hello" resource_kind="Challenge" resource_version="v1" dnsName="hello.mydomain.com" type="DNS-01" resource_name="chart-example-tls-1-3937858742-2111318442" resource_namespace="hello" resource_kind="Challenge" resource_version="v1" domain="hello.mydomain.com"
E0226 16:11:44.500764       1 controller.go:157] "re-queuing item due to error processing" err="unable to get secret `cert-manager`; unable to get secret `/cert-manager`; resource name may not be empty" logger="cert-manager.controller"
```

I created a secret (named `hetzner-secret`) in the `cert-manager` namespace which contains my DNS apiKey:

```
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-secret
  namespace: cert-manager
data:
  api-key: base64encodedapikey
```

This is the Cluster Issuer config:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: email@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          webhook:
            groupName: acme.mydomain.com
            solverName: hetzner
            config:
              zoneName: mydomain.com
              apiUrl: https://dns.hetzner.com/api/v1
```

I do not really understand the error and hope, that you can help me to solve this problem.
